# Generated by Django 4.2.9 on 2024-02-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='title',
            field=models.CharField(default=0, max_length=200, unique=True),
        ),
    ]
