# Generated by Django 4.2.9 on 2024-02-17 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='artist',
            new_name='Bio',
        ),
    ]
