# Generated by Django 4.2.9 on 2024-02-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_stars', models.IntegerField()),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
